"""removed unused field in user table

Revision ID: 29ccc7e8054e
Revises: e9fdd70f858f
Create Date: 2023-12-08 14:05:04.936932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ccc7e8054e'
down_revision = 'e9fdd70f858f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reviewed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
