"""Updated service model

Revision ID: 4cffaa7ed046
Revises: ec3b32585c1b
Create Date: 2023-11-29 20:20:31.303979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cffaa7ed046'
down_revision = 'ec3b32585c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('cv', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('sop', sa.String(length=300), nullable=True))
        batch_op.drop_column('completed_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_status', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('sop')
        batch_op.drop_column('cv')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
