"""adjusting region field

Revision ID: 50eb7f302044
Revises: c4039891257d
Create Date: 2023-11-28 21:31:34.893697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eb7f302044'
down_revision = 'c4039891257d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_region_timestamp')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('user_id')
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_index('ix_region_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
