"""Adding an application link

Revision ID: 8d2a9a30acaa
Revises: c5c8fc96d6ac
Create Date: 2023-12-04 22:30:58.056971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2a9a30acaa'
down_revision = 'c5c8fc96d6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
