"""updating post table

Revision ID: be36f1dea635
Revises: 50eb7f302044
Create Date: 2023-11-28 23:29:08.462595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be36f1dea635'
down_revision = '50eb7f302044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.String(length=64),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
