"""Adding a field for reviewed service

Revision ID: e9fdd70f858f
Revises: 64cd55aca0c6
Create Date: 2023-12-08 13:39:14.314128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9fdd70f858f'
down_revision = '64cd55aca0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_file', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('reviewed_file')

    # ### end Alembic commands ###
