"""Minor fix in post table

Revision ID: ec3b32585c1b
Revises: e0be721750b8
Create Date: 2023-11-29 13:55:43.150048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3b32585c1b'
down_revision = 'e0be721750b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement', sa.String(length=500), nullable=False))
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('requirement')

    # ### end Alembic commands ###
