"""Added a field for reviewed cv path

Revision ID: f489c4e3cc51
Revises: 8d2a9a30acaa
Create Date: 2023-12-07 14:37:25.626926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f489c4e3cc51'
down_revision = '8d2a9a30acaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_cv', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reviewed_cv')

    # ### end Alembic commands ###
